#!/usr/bin/env bash
# Dynamische Workspace-Zuweisung basierend auf angeschlossenen Monitoren.
# Wird beim Start und bei Monitor-Änderungen aufgerufen.

set -euo pipefail

INTERNAL="eDP-1"
GENERATED_CONFIG="$HOME/.config/hypr/workspaces-generated.conf"
WORKSPACE_RULES=()

monitors=$(hyprctl monitors -j | jq -r '.[].name')

has_dp2=false
has_dp3=false
external=""
external_count=0

for mon in $monitors; do
    case "$mon" in
        "$INTERNAL") ;;
        "DP-2") has_dp2=true; external_count=$((external_count + 1)) ;;
        "DP-3") has_dp3=true; external_count=$((external_count + 1)) ;;
        *) external="$mon"; external_count=$((external_count + 1)) ;;
    esac
done

generate_workspace_config() {
    printf "# Auto-generated by monitor-setup.sh — do not edit\n" > "$GENERATED_CONFIG"
    for rule in "${WORKSPACE_RULES[@]}"; do
        printf "workspace = %s\n" "$rule" >> "$GENERATED_CONFIG"
    done
}

restart_waybar() {
    killall waybar 2>/dev/null || true
    sleep 0.3
    waybar -c ~/.config/waybar/config-"$1".jsonc &
}

if $has_dp2 && $has_dp3; then
    # Szenario 2: Docking-Station — eDP-1 + DP-2 (landscape) + DP-3 (portrait)
    for ws in 1 2 3 4 5; do WORKSPACE_RULES+=("$ws, monitor:DP-2, persistent:true"); done
    for ws in 6 7;       do WORKSPACE_RULES+=("$ws, monitor:DP-3, persistent:true"); done
    for ws in 8 9;       do WORKSPACE_RULES+=("$ws, monitor:$INTERNAL, persistent:true"); done
    generate_workspace_config
    restart_waybar docked
elif [[ $external_count -eq 1 ]]; then
    # Szenario 3: Ein externer Monitor (beliebig)
    ext="${external:-DP-2}"
    $has_dp2 && ext="DP-2"
    $has_dp3 && ext="DP-3"
    for ws in 1 2 3 4 5; do WORKSPACE_RULES+=("$ws, monitor:$ext, persistent:true"); done
    for ws in 6 7 8 9;   do WORKSPACE_RULES+=("$ws, monitor:$INTERNAL, persistent:true"); done
    generate_workspace_config
    restart_waybar single
else
    # Szenario 1: Nur interner Monitor
    for ws in 1 2 3 4 5; do WORKSPACE_RULES+=("$ws, monitor:$INTERNAL, persistent:true"); done
    generate_workspace_config
    restart_waybar laptop
fi

hyprctl reload >/dev/null

# Apps nur beim ersten Start (nicht bei Monitor-Wechsel)
if [[ ! -f /tmp/hypr-apps-started ]]; then
    touch /tmp/hypr-apps-started
    hyprctl dispatch exec "[workspace 1 silent] kitty"
    hyprctl dispatch exec "[workspace 2 silent] firefox"
fi
